version: '3.3'

volumes:
  pg_database:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_database:/var/lib/postgresql/data
    restart: always

  backend:
    image: frankstotch/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      db:
        condition: service_started
    restart: always

  frontend:
    image: frankstotch/foodgram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      backend:
        condition: service_started

  nginx:
    image: frankstotch/foodgram_gateway:latest
    ports:
      - "10000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html
      - media:/usr/share/nginx/html/media
    depends_on:
      - backend
    restart: always