name: Backend tests

on:
  push:

jobs:
  tests:
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0 flake8-isort==6.0.0 isort==5.11.5
          pip install -r ./backend/requirements.txt

      - name: Test with flake8 and django tests
        env:
          POSTGRES_USER: django_user  
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
        run: |
          python -m flake8 backend/
          cd backend/
          python manage.py test

      - name: Send message if test preparation failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            Не пройдены тесты для BACKEND в репозитории [${{ github.repository }}](https://github.com/${{ github.repository }}) для интерпретатора Python ${{ matrix.python }}
            Детали:
            1. [Ссылка на Workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            2. Запушил: [${{ github.actor }}](https://github.com/${{ github.actor }})
            3. Сообщение коммита: ${{ github.event.commits[0].message }}
            4. [Ссылка на коммит](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
