# Generated by Django 3.2.25 on 2024-09-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'default_related_name': '%(class)ss', 'ordering': ('recipe', 'ingredient'), 'verbose_name': 'Продукт рецепта', 'verbose_name_plural': 'Продукты рецепта'},
        ),
    ]
